### ISSUE TITLE
VEC Info Data Issue

### ISSUE THREAD

**Issue by brandinhess** [dpurgert/pyebfgen#11]
In the Session and VEC Info screen, we need to make sure it only permits one entry per session.  At the present moment, it's allowing multiple lines for session data and the .dat files contain one line.  When the user clicks on "Apply" it should apply the data and automatically close the screen so it's all set.

**Comment by dpurgert** [comment]
I was under the impression that the FCC allowed multiple applicants per "session".  v 0.0.8 was missing a CRLF character after one of the records, it should be fixed in 0.0.9

**Comment by dpurgert** [comment]
Confirmed behaving in.
