### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by brandinhess** [dpurgert/pyebfgen#12]
Request was made to integrate a lookup window for FCC error codes after reading the .rsp file, should the application not be granted.

**Comment by dpurgert** [comment]
This can be done.  It'll take a while, there are several hundred thousand error codes in the FCC's doc; though a quick perusal seems maybe only the first 1K or so are relevant.

**Comment by dpurgert** [comment]
Added link to FCC Message Codes in the userguide.
