### ISSUE TITLE
Regional Identifier

### ISSUE THREAD

**Issue by brandinhess** [dpurgert/pyebfgen#39]
Might look at the possibility of configuring the Regional Identifier to auto-fill when the user selects the state/territory where the session actually took place.  Might help eliminate the need for users to know what their Identifier happens to be.  This would require a modification to the current list.

**Comment by dpurgert** [comment]
So, if I'm getting this right, we're assuming the users won't be setting the proper regional ID in the config file?

Or is there some caveat to the remote testing that throws a monkey wrench into that?

**Comment by dpurgert** [comment]
fixed in ed6f006
